package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Thursday 18 April 2019 at 6:10:18 PM India Standard Time
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
